spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/crawler_db
    username: crawler_admin
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port:9090