services:

  account-service:
    build:
      context: ./mot-microservices
      dockerfile: account-service/Dockerfile

  product-services:
    build:
      context: ./mot-microservices
      dockerfile: product-services/Dockerfile
      